apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-namespace.yaml
  - release-base.yaml
  - release-istiod.yaml
  # - release-gateway.yaml
  - release-logging.yaml