
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egress
spec:
  releaseName: gateway
  targetNamespace: istio-egress
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.12.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3